#!/usr/bin/env python3
"""
Aurora API submission logic for uploading generated climbs.

Uses boardlib's Aurora API to submit climbs to:
- Tension Board
- Kilter Board
- MoonBoard
"""

from typing import Dict, Any
import uuid


def submit_climb(
    board_name: str,
    username: str,
    password: str,
    frames_string: str,
    layout_id: int,
    angle: int,
    name: str,
    description: str = "Generated by BoardDiffusion",
    is_draft: bool = False,
) -> Dict[str, Any]:
    """
    Submit a generated climb to the board's API.

    Args:
        board_name: "tension", "kilter", or "moonboard"
        username: User's account username
        password: User's account password
        frames_string: Climb in Aurora frames format
        layout_id: Target layout ID
        angle: Wall angle in degrees
        name: Name for the climb
        description: Climb description
        is_draft: Whether to save as draft

    Returns:
        Dictionary with climb_uuid and status
    """
    try:
        import boardlib.api.aurora as aurora
    except ImportError:
        raise ImportError("boardlib not installed. Run: pip install boardlib")

    # Login to get session
    session = aurora.login(board_name, username, password)
    token = session["token"]
    user_id = session["user_id"]

    # Save the climb
    result = aurora.save_climb(
        board=board_name,
        token=token,
        layout_id=layout_id,
        setter_id=user_id,
        name=name,
        description=description,
        is_draft=is_draft,
        frames=frames_string,
        angle=angle,
    )

    climb_uuid = result.get("climb_uuid") or result.get("uuid")

    # Construct deep link
    deep_links = {
        "tension": f"tensionboard2://climb/{climb_uuid}",
        "kilter": f"kilterboard://climb/{climb_uuid}",
        "moonboard": f"moonboard://climb/{climb_uuid}",
    }

    return {
        "success": True,
        "climb_uuid": climb_uuid,
        "deep_link": deep_links.get(board_name, ""),
        "message": f"Climb '{name}' submitted successfully",
    }


def generate_climb_name(prefix: str = "BoardDiff") -> str:
    """Generate a unique climb name."""
    short_uuid = str(uuid.uuid4())[:8]
    return f"{prefix}_{short_uuid}"
